[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
actix-cors = "0.7"
serde_json = "1.0.149"
